version: '3'
services:
  init:
    image: karekauan/database
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_migration:
    image: karekauan/migration
    container_name: db_migration
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/school
  app:
    image: karekauan/application
    container_name: application
    ports:
      - "3333:3333"
    depends_on:
      - db_migration